name: sword
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pywin32
  - pip
  - leptonica
  - tesseract=5.2.0
  - tesserocr
  - pkg-config
  - rapidfuzz
  - pip:
    - pyinstaller
    - opencv-python==4.5.5.64
    - transitions
    - mss
    - numpy==1.26.4
    - mouse
    - keyboard
    - beautifultable
    - pytweening
    - requests
    - coverage
    - pytest
    - pytest-env
    - pytest-pythonpath
    - pytest-mock
    - graphviz
    - psutil
    - cryptography
    - pillow
    - discord.py==1.7.3
    - aiohttp==3.7.4.post0
    - parse
    - typing_extensions
    - colorama
    - dataclasses-json
    - pyparsing